rails_app/config/routes.rb
Rails.application.routes.draw do
  resources :references
  resources :skills
  resources :honors
  resources :works
  resources :courses
  devise_for :users
  get 'dashboard/index'

  get 'dashboard/page1'

  get 'dashboard/page2'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "dashboard#index"
  get 'dashboard/index'
  get 'dashboard/page1'
  get 'dashboard/page2'
  get 'dashboard/page3'
  get 'dashboard/page4'
  get 'dashboard/page5'
  get 'dashboard/page6'
  get 'dashboard/page7'
end

rails_app/app/models/work.rb
class Work < ApplicationRecord
end

rails_app/app/controllers/works_controller.rb
class WorksController < ApplicationController
  before_action :set_work, only: [:show, :edit, :update, :destroy]

  # GET /works
  # GET /works.json
  def index
    @works = Work.all
  end

  # GET /works/1
  # GET /works/1.json
  def show
  end

  # GET /works/new
  def new
    @work = Work.new
  end

  # GET /works/1/edit
  def edit
  end

  # POST /works
  # POST /works.json
  def create
    @work = Work.new(work_params)

    respond_to do |format|
      if @work.save
        format.html { redirect_to @work, notice: 'Work was successfully created.' }
        format.json { render :show, status: :created, location: @work }
      else
        format.html { render :new }
        format.json { render json: @work.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /works/1
  # PATCH/PUT /works/1.json
  def update
    respond_to do |format|
      if @work.update(work_params)
        format.html { redirect_to @work, notice: 'Work was successfully updated.' }
        format.json { render :show, status: :ok, location: @work }
      else
        format.html { render :edit }
        format.json { render json: @work.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /works/1
  # DELETE /works/1.json
  def destroy
    @work.destroy
    respond_to do |format|
      format.html { redirect_to works_url, notice: 'Work was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_work
      @work = Work.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def work_params
      params.require(:work).permit(:owner, :start_date, :end_date, :name, :description)
    end
end

rails_app/app/helpers/works_helper.rb
module WorksHelper
end

rails_app/app/views/works/_form.html.erb
<%= form_for(work) do |f| %>
  <% if work.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(work.errors.count, "error") %> prohibited this work from being saved:</h2>

      <ul>
      <% work.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <form class="form-inline">

  <div class="form-group">
    <%= f.hidden_field :owner, :value => current_user.id %>
  </div>

  <div class="form-group">
    <%= f.label :start_date %>
    <%= f.text_field :start_date %>
  </div>

  <div class="form-group">
    <%= f.label :end_date %>
    <%= f.text_field :end_date %>
  </div>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
  </form>
<% end %>

rails_app/app/views/works/edit.html.erb
<h1>Editing Work</h1>

<form class="form-inline">
<%= render 'form', work: @work%>
</form>

<%= link_to 'Show', @work %> |
<%= link_to 'Back', works_path %>

rails_app/app/views/works/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Works</h1>

<table>
  <thead>
    <tr>
      <th>Owner</th>
      <th>Start date</th>
      <th>End date</th>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @works.each do |work| %>
      <tr>
        <td><%= work.owner %></td>
        <td><%= work.start_date %></td>
        <td><%= work.end_date %></td>
        <td><%= work.name %></td>
        <td><%= work.description %></td>
        <td><%= link_to 'Show', work %></td>
        <td><%= link_to 'Edit', edit_work_path(work) %></td>
        <td><%= link_to 'Destroy', work, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Work', new_work_path %>

rails_app/app/views/works/new.html.erb
<h1>New Work</h1>

<form class="form-inline">
<%= render 'form', work: @work %>
</form>

<%= link_to 'Back', works_path %>

rails_app/app/views/works/show.html.erb
<p id="notice"><%= notice %></p>

<form class="form-inline">

<p class="form-group">
  <strong>Owner:</strong>
  <%= @work.owner %>
</p>

<p class="form-group">
  <strong>Start date:</strong>
  <%= @work.start_date %>
</p>

<p class="form-group">
  <strong>End date:</strong>
  <%= @work.end_date %>
</p>

<p class="form-group">
  <strong>Name:</strong>
  <%= @work.name %>
</p>

<p class="form-group">
  <strong>Description:</strong>
  <%= @work.description %>
</p>

</form>

<%= link_to 'Edit', edit_work_path(@work) %> |
<%= link_to 'Back', works_path %>