rails_app/config/routes.rb
Rails.application.routes.draw do
  resources :references
  resources :skills
  resources :honors
  resources :works
  resources :courses
  devise_for :users
  get 'dashboard/index'

  get 'dashboard/page1'

  get 'dashboard/page2'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "dashboard#index"
  get 'dashboard/index'
  get 'dashboard/page1'
  get 'dashboard/page2'
  get 'dashboard/page3'
  get 'dashboard/page4'
  get 'dashboard/page5'
  get 'dashboard/page6'
  get 'dashboard/page7'
end

rails_app/app/models/honor.rb
class Honor < ApplicationRecord
end

rails_app/app/controllers/honors_controller.rb
class HonorsController < ApplicationController
  before_action :set_honor, only: [:show, :edit, :update, :destroy]

  # GET /honors
  # GET /honors.json
  def index
    @honors = Honor.all
  end

  # GET /honors/1
  # GET /honors/1.json
  def show
  end

  # GET /honors/new
  def new
    @honor = Honor.new
  end

  # GET /honors/1/edit
  def edit
  end

  # POST /honors
  # POST /honors.json
  def create
    @honor = Honor.new(honor_params)

    respond_to do |format|
      if @honor.save
        format.html { redirect_to @honor, notice: 'Honor was successfully created.' }
        format.json { render :show, status: :created, location: @honor }
      else
        format.html { render :new }
        format.json { render json: @honor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /honors/1
  # PATCH/PUT /honors/1.json
  def update
    respond_to do |format|
      if @honor.update(honor_params)
        format.html { redirect_to @honor, notice: 'Honor was successfully updated.' }
        format.json { render :show, status: :ok, location: @honor }
      else
        format.html { render :edit }
        format.json { render json: @honor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /honors/1
  # DELETE /honors/1.json
  def destroy
    @honor.destroy
    respond_to do |format|
      format.html { redirect_to honors_url, notice: 'Honor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_honor
      @honor = Honor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def honor_params
      params.require(:honor).permit(:owner, :honor_date, :honor_name, :honor_description)
    end
end

rails_app/app/helpers/honors_helper.rb
module HonorsHelper
end

rails_app/app/views/honors/_form.html.erb
<%= form_for(honor) do |f| %>
  <% if honor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(honor.errors.count, "error") %> prohibited this honor from being saved:</h2>

      <ul>
      <% honor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.hidden_field :owner, :value => current_user.id %>
  </div>

  <div class="field">
    <%= f.label :honor_date %>
    <%= f.text_field :honor_date %>
  </div>

  <div class="field">
    <%= f.label :honor_name %>
    <%= f.text_field :honor_name %>
  </div>

  <div class="field">
    <%= f.label :honor_description %>
    <%= f.text_field :honor_description %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

rails_app/app/views/honors/edit.html.erb
<h1>Editing Honor</h1>

<%= render 'form', honor: @honor %>

<%= link_to 'Show', @honor %> |
<%= link_to 'Back', honors_path %>

rails_app/app/views/honors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Honors</h1>

<table>
  <thead>
    <tr>
      <th>Owner</th>
      <th>Honor date</th>
      <th>Honor name</th>
      <th>Honor description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @honors.each do |honor| %>
      <tr>
        <td><%= honor.owner %></td>
        <td><%= honor.honor_date %></td>
        <td><%= honor.honor_name %></td>
        <td><%= honor.honor_description %></td>
        <td><%= link_to 'Show', honor %></td>
        <td><%= link_to 'Edit', edit_honor_path(honor) %></td>
        <td><%= link_to 'Destroy', honor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Honor', new_honor_path %>

rails_app/app/views/honors/new.html.erb
<h1>New Honor</h1>

<%= render 'form', honor: @honor %>

<%= link_to 'Back', honors_path %>

rails_app/app/views/honors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Owner:</strong>
  <%= @honor.owner %>
</p>

<p>
  <strong>Honor date:</strong>
  <%= @honor.honor_date %>
</p>

<p>
  <strong>Honor name:</strong>
  <%= @honor.honor_name %>
</p>

<p>
  <strong>Honor description:</strong>
  <%= @honor.honor_description %>
</p>

<%= link_to 'Edit', edit_honor_path(@honor) %> |
<%= link_to 'Back', honors_path %>