rails_app/config/routes.rb
Rails.application.routes.draw do
  resources :references
  resources :skills
  resources :honors
  resources :works
  resources :courses
  devise_for :users
  get 'dashboard/index'

  get 'dashboard/page1'

  get 'dashboard/page2'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "dashboard#index"
  get 'dashboard/index'
  get 'dashboard/page1'
  get 'dashboard/page2'
  get 'dashboard/page3'
  get 'dashboard/page4'
  get 'dashboard/page5'
  get 'dashboard/page6'
  get 'dashboard/page7'
end

rails_app/app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
    if user_signed_in?
     @user = User.find(current_user.id)
     @courses = Course.where("owner = ?", current_user.id)
     @works = Work.where("owner = ?", current_user.id)
     @honors = Honor.where("owner = ?", current_user.id)
     @skills = Skill.where("owner = ?", current_user.id)
     @references = Reference.where("owner = ?", current_user.id)
    end
  end

  def page1
  end

  def page2
      @user = User.find(current_user.id)
      @courses = Course.where("owner = ?", current_user.id)
  end
  
  def page3
    @user = User.find(current_user.id)
    @works = Work.where("owner = ?", current_user.id)
  end
  
  def page4
    @user = User.find(current_user.id)
    @honors = Honor.where("owner = ?", current_user.id)
  end
  
  def page5
    @user = User.find(current_user.id)
    @skills = Skill.where("owner = ?", current_user.id)
  end
  
  def page6
    @user = User.find(current_user.id)
    @references = Reference.where("owner = ?", current_user.id)
  end
  
  def page7
    user = User.find(current_user.id)
    @experiences = Work.where("owner = ?", current_user.id)
    @skills = Skill.where("owner = ?", current_user.id)
    @honors = Honor.where("owner = ?", current_user.id)
    @references = Reference.where("owner = ?", current_user.id)
    
    Caracal::Document.save '/public/Resume.docx' do |docx|
      
    docx.style do
      id 'Body'
      name 'body'
      font 'Times New Roman'
      size 18
    end
    
    docx.h2 'User Info'
    docx.p do
      style 'Body'
      text 'Name: '
      text user.first_name
      text ' '
      text user.last_name
      br
      text 'Major: '
      text user.major
      br
    end
    
    
    docx.h2 'Experience'
    @experiences.each do | experience |
      docx.p do
        style 'Body'
        text experience.name
        text ": "
        text experience.description
        br
      end
    end
    
    docx.h2 'Skills'
    @skills.each do | skill |
      docx.p do
        style 'Body'
        text skill.skill_name
        text ": "
        text skill.skill_description
        br
      end
    end
    
    docx.h2 'Honors'
    @honors.each do | honor |
      docx.p do
        style 'Body'
        text honor.honor_name
        text ": "
        text honor.honor_description
        br
      end
    end
    
    docx.h2 'References'
    @references.each do | reference |
      docx.p do
        style 'Body'
        text reference.reference_name
        text ": "
        text reference.reference_contact_info
        br
      end
    end
  end
  
  path = File.join(Rails.root, "public")
  send_file(File.join(path, "Resume.docx"))
  
    end
end

rails_app/app/helpers/dashboard_helper.rb
module DashboardHelper
end

rails_app/app/views/dashboard/index.html.erb
<h1>Header text</h1>
<p>I am some body text!</p>

<% if user_signed_in? %>
<%= link_to "Display Courses", { :controller => :dashboard, :action => :page2 },
 class: "btn btn-default" %>
 <br/>
<%= link_to "Display Work", { :controller => :dashboard, :action => :page3 },
 class: "btn btn-default" %>
 <br/>
<%= link_to "Display Honors", { :controller => :dashboard, :action => :page4},
 class: "btn btn-default" %>
 <br/>
<%= link_to "Display Skills", { :controller => :dashboard, :action => :page5 },
 class: "btn btn-default" %>
 <br/>
<%= link_to "Display References", { :controller => :dashboard, :action => :page6 },
 class: "btn btn-default" %>
 
 <%= link_to "Download Document", { :controller => :dashboard, :action => :page7 },
 class: "btn btn-default" %>


<h1>Courses</h1>

<table>
  <thead>
    <tr>
      <th>Owner</th>
      <th>Course number</th>
      <th>Course name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody id="courseList">
    <% @courses.each do |course| %>
      <tr data-toggle="modal" data-target="#myModal">
        <td><%= course.owner %></td>
        <td><%= course.course_number %></td>
        <td><%= course.course_name %></td>
        <td><%= link_to 'Show', course %></td>
        <td><%= link_to 'Edit', edit_course_path(course) %></td>
        <td><%= link_to 'Destroy', course, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Course', new_course_path %>


<h1>Works</h1>

<table>
  <thead>
    <tr>
      <th>Owner</th>
      <th>Start date</th>
      <th>End date</th>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody id="workList">
    <% @works.each do |work| %>
      <tr data-toggle="modal" data-target="#myModal">
        <td><%= work.owner %></td>
        <td><%= work.start_date %></td>
        <td><%= work.end_date %></td>
        <td><%= work.name %></td>
        <td><%= work.description %></td>
        <td><%= link_to 'Show', work %></td>
        <td><%= link_to 'Edit', edit_work_path(work) %></td>
        <td><%= link_to 'Destroy', work, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Work', new_work_path %>


<h1>Honors</h1>

<table>
  <thead>
    <tr>
      <th>Owner</th>
      <th>Honor date</th>
      <th>Honor name</th>
      <th>Honor description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody id = "honorList">
    <% @honors.each do |honor| %>
      <tr data-toggle="modal" data-target="#myModal">
        <td><%= honor.owner %></td>
        <td><%= honor.honor_date %></td>
        <td><%= honor.honor_name %></td>
        <td><%= honor.honor_description %></td>
        <td><%= link_to 'Show', honor %></td>
        <td><%= link_to 'Edit', edit_honor_path(honor) %></td>
        <td><%= link_to 'Destroy', honor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Honor', new_honor_path %>

<h1>Skills</h1>

<table>
  <thead>
    <tr>
      <th>Owner</th>
      <th>Skill name</th>
      <th>Skill description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody id="skillList">
    <% @skills.each do |skill| %>
      <tr data-toggle="modal" data-target="#myModal">
        <td><%= skill.owner %></td>
        <td><%= skill.skill_name %></td>
        <td><%= skill.skill_description %></td>
        <td><%= link_to 'Show', skill %></td>
        <td><%= link_to 'Edit', edit_skill_path(skill) %></td>
        <td><%= link_to 'Destroy', skill, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Skill', new_skill_path %>

<h1>References</h1>

<table>
  <thead>
    <tr>
      <th>Owner</th>
      <th>Reference name</th>
      <th>Reference contact info</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody id="refList">
    <% @references.each do |reference| %>
      <tr data-toggle="modal" data-target="#myModal">
        <td><%= reference.owner %></td>
        <td><%= reference.reference_name %></td>
        <td><%= reference.reference_contact_info %></td>
        <td><%= link_to 'Show', reference %></td>
        <td><%= link_to 'Edit', edit_reference_path(reference) %></td>
        <td><%= link_to 'Destroy', reference, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Reference', new_reference_path %>

<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
 <div class="modal-dialog" role="document">
  <div class="modal-content">
   <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <h4 class="modal-title" id="myModalLabel">label</h4>
   </div>
   <div class="modal-body" id="myModalBody">
    ...
   </div>
  </div>
 </div>
</div>

<% end %>

rails_app/app/views/dashboard/page1.html.erb
<h1>Page 1!</h1>
<p>this is a first page</p>

rails_app/app/views/dashboard/page2.html.erb
<h1>Page 2!</h1>
<p>this is a second page</p>


Hello, <%= @user.first_name %>!

<table>
  <thead>
    <tr>
      <th>Owner</th>
      <th>Course number</th>
      <th>Course name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @courses.each do |course| %>
      <tr>
        <td><%= course.owner %></td>
        <td><%= course.course_number %></td>
        <td><%= course.course_name %></td>
        <td><%= link_to 'Show', course %></td>
        <td><%= link_to 'Edit', edit_course_path(course) %></td>
        <td><%= link_to 'Destroy', course, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Course', new_course_path %>

rails_app/app/views/dashboard/page3.html.erb
<h1>Works</h1>

<table>
  <thead>
    <tr>
      <th>Owner</th>
      <th>Start date</th>
      <th>End date</th>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @works.each do |work| %>
      <tr>
        <td><%= work.owner %></td>
        <td><%= work.start_date %></td>
        <td><%= work.end_date %></td>
        <td><%= work.name %></td>
        <td><%= work.description %></td>
        <td><%= link_to 'Show', work %></td>
        <td><%= link_to 'Edit', edit_work_path(work) %></td>
        <td><%= link_to 'Destroy', work, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Work', new_work_path %>

rails_app/app/views/dashboard/page4.html.erb
<h1>Honors</h1>

<table>
  <thead>
    <tr>
      <th>Owner</th>
      <th>Honor date</th>
      <th>Honor name</th>
      <th>Honor description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @honors.each do |honor| %>
      <tr>
        <td><%= honor.owner %></td>
        <td><%= honor.honor_date %></td>
        <td><%= honor.honor_name %></td>
        <td><%= honor.honor_description %></td>
        <td><%= link_to 'Show', honor %></td>
        <td><%= link_to 'Edit', edit_honor_path(honor) %></td>
        <td><%= link_to 'Destroy', honor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Honor', new_honor_path %>

rails_app/app/views/dashboard/page5.html.erb
<h1>Skills</h1>

<table>
  <thead>
    <tr>
      <th>Owner</th>
      <th>Skill name</th>
      <th>Skill description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @skills.each do |skill| %>
      <tr>
        <td><%= skill.owner %></td>
        <td><%= skill.skill_name %></td>
        <td><%= skill.skill_description %></td>
        <td><%= link_to 'Show', skill %></td>
        <td><%= link_to 'Edit', edit_skill_path(skill) %></td>
        <td><%= link_to 'Destroy', skill, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Skill', new_skill_path %>

rails_app/app/views/dashboard/page6.html.erb
<h1>References</h1>

<table>
  <thead>
    <tr>
      <th>Owner</th>
      <th>Reference name</th>
      <th>Reference contact info</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @references.each do |reference| %>
      <tr>
        <td><%= reference.owner %></td>
        <td><%= reference.reference_name %></td>
        <td><%= reference.reference_contact_info %></td>
        <td><%= link_to 'Show', reference %></td>
        <td><%= link_to 'Edit', edit_reference_path(reference) %></td>
        <td><%= link_to 'Destroy', reference, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Reference', new_reference_path %>

rails_app/app/views/dashboard/page7.html.erb
<h1>Download Document</h1>

This is a page.