rails_app/config/routes.rb
Rails.application.routes.draw do
  resources :references
  resources :skills
  resources :honors
  resources :works
  resources :courses
  devise_for :users
  get 'dashboard/index'

  get 'dashboard/page1'

  get 'dashboard/page2'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "dashboard#index"
  get 'dashboard/index'
  get 'dashboard/page1'
  get 'dashboard/page2'
  get 'dashboard/page3'
  get 'dashboard/page4'
  get 'dashboard/page5'
  get 'dashboard/page6'
  get 'dashboard/page7'
end

rails_app/app/models/reference.rb
class Reference < ApplicationRecord
end

rails_app/app/controllers/references_controller.rb
class ReferencesController < ApplicationController
  before_action :set_reference, only: [:show, :edit, :update, :destroy]

  # GET /references
  # GET /references.json
  def index
    @references = Reference.all
  end

  # GET /references/1
  # GET /references/1.json
  def show
  end

  # GET /references/new
  def new
    @reference = Reference.new
  end

  # GET /references/1/edit
  def edit
  end

  # POST /references
  # POST /references.json
  def create
    @reference = Reference.new(reference_params)

    respond_to do |format|
      if @reference.save
        format.html { redirect_to @reference, notice: 'Reference was successfully created.' }
        format.json { render :show, status: :created, location: @reference }
      else
        format.html { render :new }
        format.json { render json: @reference.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /references/1
  # PATCH/PUT /references/1.json
  def update
    respond_to do |format|
      if @reference.update(reference_params)
        format.html { redirect_to @reference, notice: 'Reference was successfully updated.' }
        format.json { render :show, status: :ok, location: @reference }
      else
        format.html { render :edit }
        format.json { render json: @reference.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /references/1
  # DELETE /references/1.json
  def destroy
    @reference.destroy
    respond_to do |format|
      format.html { redirect_to references_url, notice: 'Reference was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reference
      @reference = Reference.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def reference_params
      params.require(:reference).permit(:owner, :reference_name, :reference_contact_info)
    end
end

rails_app/app/helpers/references_helper.rb
module ReferencesHelper
end

rails_app/app/views/references/_form.html.erb
<%= form_for(reference) do |f| %>
  <% if reference.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(reference.errors.count, "error") %> prohibited this reference from being saved:</h2>

      <ul>
      <% reference.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.hidden_field :owner, :value => current_user.id %>
  </div>

  <div class="field">
    <%= f.label :reference_name %>
    <%= f.text_field :reference_name %>
  </div>

  <div class="field">
    <%= f.label :reference_contact_info %>
    <%= f.text_field :reference_contact_info %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

rails_app/app/views/references/edit.html.erb
<h1>Editing Reference</h1>

<%= render 'form', reference: @reference %>

<%= link_to 'Show', @reference %> |
<%= link_to 'Back', references_path %>

rails_app/app/views/references/index.html.erb
<p id="notice"><%= notice %></p>

<h1>References</h1>

<table>
  <thead>
    <tr>
      <th>Owner</th>
      <th>Reference name</th>
      <th>Reference contact info</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @references.each do |reference| %>
      <tr>
        <td><%= reference.owner %></td>
        <td><%= reference.reference_name %></td>
        <td><%= reference.reference_contact_info %></td>
        <td><%= link_to 'Show', reference %></td>
        <td><%= link_to 'Edit', edit_reference_path(reference) %></td>
        <td><%= link_to 'Destroy', reference, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Reference', new_reference_path %>

rails_app/app/views/references/new.html.erb
<h1>New Reference</h1>

<%= render 'form', reference: @reference %>

<%= link_to 'Back', references_path %>

rails_app/app/views/references/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Owner:</strong>
  <%= @reference.owner %>
</p>

<p>
  <strong>Reference name:</strong>
  <%= @reference.reference_name %>
</p>

<p>
  <strong>Reference contact info:</strong>
  <%= @reference.reference_contact_info %>
</p>

<%= link_to 'Edit', edit_reference_path(@reference) %> |
<%= link_to 'Back', references_path %>